import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {NextUIProvider} from "@nextui-org/react";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { GetUserProvider } from "./Context/GetUserContext";
import {Toaster} from 'react-hot-toast'
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Task io",
  description: "Generated by create next app",
};
const client_id=process.env.CLIENT_ID
console.log(client_id)
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 

{
  return (
    <html lang="en">
      <body className={inter.className}>
     
     <GoogleOAuthProvider clientId={client_id?client_id:""}>
     <NextUIProvider>
     <Toaster position="top-right" />
        <main className="dark  ">
          {children}
          </main>
      
       </NextUIProvider>
     </GoogleOAuthProvider>
       </body>
    </html>
  );
}
